<a href="https://colab.research.google.com/github/vic-fmr/ecommerce-analytics/blob/main/codigo/analise_ecommerce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1 - Setup

Está seção é responsavel por setar tudo que é necessário para o projeto rodar, como clone e leitura de arquivos.

## 1.1. Configuração (Clone e Imports)

In [1]:
print("Clonando repo para ter acesso a pasta dados/")

# Esse clone é apenas para o codigo ter acesso á pasta dados/, para salvar
# mudanças, seguir: Arquivo -> Salvar (confimar caminho: codigo/analise_ecommerce.ipynb e adicionar mensagem
# de commit)

!git clone https://github.com/vic-fmr/ecommerce-analytics.git

import pandas as pd
import os

Clonando repo para ter acesso a pasta dados/
Cloning into 'ecommerce-analytics'...
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 72 (delta 24), reused 3 (delta 0), pack-reused 22 (from 2)
Receiving objects: 100% (72/72), 42.35 MiB | 27.75 MiB/s, done.
Resolving deltas: 100% (24/24), done.

## 1.2. Carga dos DataFrames

In [11]:


DATA_PATH = "/content/ecommerce-analytics/dados"

arquivos = {
    "clientes": "DIM_Customer.csv",
    "entregas": "DIM_Delivery.csv",
    "produtos": "DIM_Products.csv",
    "pedidos": "FACT_Orders.csv",
    "compras": "DIM_Shopping.csv",
}

dataframes = {}

## 1.3. Exploração Inicial (info(), head())

In [13]:
print("--- 1. Carregando Datasets ---")

# Carrega cada arquivo CSV e armazena no dicionário 'dataframes'
for nome, arquivo in arquivos.items():
    caminho_completo = os.path.join(DATA_PATH, arquivo)
    try:
        dataframes[nome] = pd.read_csv(caminho_completo)
        print(f"✅ Arquivo '{arquivo}' carregado com sucesso como 'dataframes['{nome}']'.")
    except FileNotFoundError:
        print(f"❌ ERRO: Arquivo '{arquivo}' não encontrado no caminho '{caminho_completo}'.")
        print("Por favor, verifique o DATA_PATH e o nome do arquivo.")

print("\n--- 2. Exploração Inicial (Shape, Colunas, Tipos e Nulos) ---")


def explorar_df(nome, df):
    print("\n" + "="*50)
    print(f" DataFrame: {nome}")
    print(f" Formato (Linhas, Colunas): {df.shape}")
    print("="*50)

    print(f"\n[Info: Colunas, Contagem de Nulos e Tipos de Dados]")
    df.info()

    print(f"\n[Head: 3 primeiras linhas]")
    display(df.head(3))
    print("\n")


# Se os dataframes foram carregados, executa a exploração
if dataframes:
    for nome, df in dataframes.items():
        explorar_df(nome, df)
else:
    print("Nenhum dataframe foi carregado. A exploração foi interrompida.")

--- 1. Carregando Datasets ---
✅ Arquivo 'DIM_Customer.csv' carregado com sucesso como 'dataframes['clientes']'.
✅ Arquivo 'DIM_Delivery.csv' carregado com sucesso como 'dataframes['entregas']'.
✅ Arquivo 'DIM_Products.csv' carregado com sucesso como 'dataframes['produtos']'.
✅ Arquivo 'FACT_Orders.csv' carregado com sucesso como 'dataframes['pedidos']'.
✅ Arquivo 'DIM_Shopping.csv' carregado com sucesso como 'dataframes['compras']'.

--- 2. Exploração Inicial (Shape, Colunas, Tipos e Nulos) ---

==================================================
 DataFrame: clientes
 Formato (Linhas, Colunas): (2000, 6)
==================================================

[Info: Colunas, Contagem de Nulos e Tipos de Dados]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2000 non-null   int64
 1   Customer_Id    2000 non-null   object
 2   Customer_Name  2000 non-null   object
 3   City           2000 non-null   object
 4   State          2000 non-null   object
 5   Region         2000 non-null   object
dtypes: int64(1), object(5)
memory usage: 93.9+ KB

[Head: 3 primeiras linhas]

   Id Customer_Id      Customer_Name            City State    Region
0   1      C00001  Catarina Oliveira  Sena Madureira    AC     Norte
1   2      C00002         Igor Cunha  Campina Grande    PB  Nordeste
2   3      C00003       Isis Barbosa           Cantá    RR     Norte

==================================================
 DataFrame: entregas
 Formato (Linhas, Colunas): (2000, 7)
==================================================

[Info: Colunas, Contagem de Nulos e Tipos de Dados]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           2000 non-null   int64
 1   Delivery_Id  2000 non-null   object
 2   Services     2000 non-null   object
 3   P_Sevice     2000 non-null   float64
 4   D_Forecast   2000 non-null   object
 5   D_Date       2000 non-null   object
 6   Status       2000 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 109.5+ KB

[Head: 3 primeiras linhas]

,Id,Delivery_Id,Services,P_Sevice,D_Forecast,D_Date,Status
0,1,D00001,Same-Day,42.9,2025-05-03 14:45:17,2025-05-03 14:45:17,A Caminho
1,2,D00002,Same-Day,42.9,2025-05-14 07:31:07,2025-05-17 07:31:07,Entregue
2,3,D00003,Standard,22.9,2025-05-10 15:29:43,2025-05-10 15:29:43,A Caminho

==================================================
 DataFrame: produtos
 Formato (Linhas, Colunas): (21, 6)
==================================================

[Info: Colunas, Contagem de Nulos e Tipos de Dados]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            21 non-null     int64
 1   Product_Id    21 non-null     object
 2   Product_Name  21 non-null     object
 3   Category      21 non-null     object
 4   Subcategory   21 non-null     object
 5   Price         21 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB

[Head: 3 primeiras linhas]

,Id,Product_Id,Product_Name,Category,Subcategory,Price
0,1,P0001,Samsung Galaxy A36,Eletrônicos,"Celulares, Tablets e Acessórios",1979.10
1,2,P0002,Samsung Galaxy Tab S6 Lite,Eletrônicos,"Celulares, Tablets e Acessórios",1799.01
2,3,P0003,Carregador Turbo USB-C 30W,Eletrônicos,"Celulares, Tablets e Acessórios",49.90

==================================================
 DataFrame: pedidos
 Formato (Linhas, Colunas): (2000, 7)
==================================================

[Info: Colunas, Contagem de Nulos e Tipos de Dados]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               2000 non-null   int64
 1   Order_Date       2000 non-null   object
 2   Discount         2000 non-null   float64
 3   Subtotal         2000 non-null   float64
 4   Total            2000 non-null   float64
 5   payment          2000 non-null   object
 6   Purchase_Status  2000 non-null   object
dtypes: float64(3), int64(1), object(3)
memory usage: 109.5+ KB

[Head: 3 primeiras linhas]

,Id,Order_Date,Discount,Subtotal,Total,payment,Purchase_Status
0,1,2025-04-12 00:52:33,0.1048,3958.20,3586.28,Credito,Processando
1,2,2025-05-05 01:02:38,0.1141,1799.01,1636.64,PIX,Em Analise
2,3,2025-04-27 23:05:38,0.0686,2144.00,2019.82,Boleto,Cancelado

==================================================
 DataFrame: compras
 Formato (Linhas, Colunas): (2000, 5)
==================================================

[Info: Colunas, Contagem de Nulos e Tipos de Dados]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Id        2000 non-null   int64
 1   Item_ID   2000 non-null   object
 2   Product   2000 non-null   object
 3   Quantity  2000 non-null   int64
 4   Price     2000 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 78.3+ KB

[Head: 3 primeiras linhas]

,Id,Item_ID,Product,Quantity,Price
0,1,I00001,Samsung Galaxy A36,2,1979.10
1,2,I00002,Samsung Galaxy Tab S6 Lite,1,1799.01
2,3,I00003,"Soundbar Samsung com 2.1 canais, Dolby Digital",2,1072.00

# 2. [S1] Data Cleaning (Tipos, NAs, Strings)

Seção de limpeza e verificação de dados.

## 2.1. Correção de Tipos (Datas e Numéricos)

In [14]:
print("\n--- 2.1. Correção de Tipos: Datas ---")

colunas_de_data = {
    'entregas': ['D_Forecast', 'D_Date'],
    'pedidos': ['Order_Date']
}

for nome_df, df in dataframes.items():
    if nome_df in colunas_de_data:
        print(f"\n🚀 Processando DataFrame: {nome_df}")

        # Filtrar apenas as colunas que realmente existem no DataFrame
        colunas_para_converter = [col for col in colunas_de_data[nome_df] if col in df.columns]

        if colunas_para_converter:
            print(f"   Colunas identificadas para conversão: {colunas_para_converter}")

            for col in colunas_para_converter:
                # O parâmetro 'errors='coerce'' transformará valores que não são datas válidas em NaT (Not a Time/Date),
                # o que facilita a identificação e tratamento de erros posteriormente.
                df[col] = pd.to_datetime(df[col], errors='coerce')
                print(f"   ✅ Coluna '{col}' convertida para tipo datetime64[ns].")

            dataframes[nome_df] = df
        else:
            print(f"   Nenhuma coluna de data predefinida encontrada em '{nome_df}'.")
    else:
        print(f"\n   DataFrame '{nome_df}' não possui colunas de data pré-mapeadas neste passo.")

#Re-executar a exploração para ver os novos tipos
print("\n" + "="*70)
print("\n🚀Re-executando exploração de dataframes com colunas de data após:")
for nome, df in dataframes.items():
    if nome in colunas_de_data:
        explorar_df(nome, df)

print("\n" + "="*70)
print("\n--- 2.1. Correção de Tipos: Numéricos ---")

colunas_numericas = {
    'clientes': ['Id'],
    'entregas': ['Id', 'P_Sevice'],
    'produtos': ['Id', 'Price'],
    'pedidos': ['Id', 'Discount', 'Subtotal', 'Total'],
    'compras': ['Id', 'Quantity', 'Price']
}

for nome_df, df in dataframes.items():
    if nome_df in colunas_numericas:
        print(f"\n🚀 Processando DataFrame: {nome_df}")

        # Filtrar apenas as colunas que realmente existem no DataFrame
        colunas_para_converter = [col for col in colunas_numericas[nome_df] if col in df.columns]

        if colunas_para_converter:
            for col in colunas_para_converter:
                # Converte para float, o parâmetro 'errors='coerce'' transforma
                # qualquer valor que não seja numérico em NaN (Not a Number).
                df[col] = pd.to_numeric(df[col], errors='coerce')
                print(f"   ✅ Coluna '{col}' convertida para tipo numérico (float64) com erros forçados a NaN.")

            dataframes[nome_df] = df
        else:
            print(f"   Nenhuma coluna numérica predefinida encontrada em '{nome_df}'.")

--- 2.1. Correção de Tipos: Datas ---

   DataFrame 'clientes' não possui colunas de data pré-mapeadas neste passo.

🚀 Processando DataFrame: entregas
   Colunas identificadas para conversão: ['D_Forecast', 'D_Date']
   ✅ Coluna 'D_Forecast' convertida para tipo datetime64[ns].
   ✅ Coluna 'D_Date' convertida para tipo datetime64[ns].

   DataFrame 'produtos' não possui colunas de data pré-mapeadas neste passo.

🚀 Processando DataFrame: pedidos
   Colunas identificadas para conversão: ['Order_Date']
   ✅ Coluna 'Order_Date' convertida para tipo datetime64[ns].

   DataFrame 'compras' não possui colunas de data pré-mapeadas neste passo.

======================================================================

🚀Re-executando exploração de dataframes com colunas de data após:

==================================================
 DataFrame: entregas
 Formato (Linhas, Colunas): (2000, 7)
==================================================

[Info: Colunas, Contagem de Nulos e Tipos de Dados]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           2000 non-null   int64
 1   Delivery_Id  2000 non-null   object
 2   Services     2000 non-null   object
 3   P_Sevice     2000 non-null   float64
 4   D_Forecast   2000 non-null   datetime64[ns]
 5   D_Date       2000 non-null   datetime64[ns]
 6   Status       2000 non-null   object
dtypes: datetime64[ns](2), float64(1), int64(1), object(3)
memory usage: 109.5+ KB

[Head: 3 primeiras linhas]

,Id,Delivery_Id,Services,P_Sevice,D_Forecast,D_Date,Status
0,1,D00001,Same-Day,42.9,2025-05-03 14:45:17,2025-05-03 14:45:17,A Caminho
1,2,D00002,Same-Day,42.9,2025-05-14 07:31:07,2025-05-17 07:31:07,Entregue
2,3,D00003,Standard,22.9,2025-05-10 15:29:43,2025-05-10 15:29:43,A Caminho

==================================================
 DataFrame: pedidos
 Formato (Linhas, Colunas): (2000, 7)
==================================================

[Info: Colunas, Contagem de Nulos e Tipos de Dados]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               2000 non-null   int64
 1   Order_Date       2000 non-null   datetime64[ns]
 2   Discount         2000 non-null   float64
 3   Subtotal         2000 non-null   float64
 4   Total            2000 non-null   float64
 5   payment          2000 non-null   object
 6   Purchase_Status  2000 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(1), object(2)
memory usage: 109.5+ KB

[Head: 3 primeiras linhas]

,Id,Order_Date,Discount,Subtotal,Total,payment,Purchase_Status
0,1,2025-04-12 00:52:33,0.1048,3958.20,3586.28,Credito,Processando
1,2,2025-05-05 01:02:38,0.1141,1799.01,1636.64,PIX,Em Analise
2,3,2025-04-27 23:05:38,0.0686,2144.00,2019.82,Boleto,Cancelado

======================================================================

--- 2.1. Correção de Tipos: Numéricos ---

🚀 Processando DataFrame: clientes
   ✅ Coluna 'Id' convertida para tipo numérico (float64) com erros forçados a NaN.

🚀 Processando DataFrame: entregas
   ✅ Coluna 'Id' convertida para tipo numérico (float64) com erros forçados a NaN.
   ✅ Coluna 'P_Sevice' convertida para tipo numérico (float64) com erros forçados a NaN.

🚀 Processando DataFrame: produtos
   ✅ Coluna 'Id' convertida para tipo numérico (float64) com erros forçados a NaN.
   ✅ Coluna 'Price' convertida para tipo numérico (float64) com erros forçados a NaN.

🚀 Processando DataFrame: pedidos
   ✅ Coluna 'Id' convertida para tipo numérico (float64) com erros forçados a NaN.
   ✅ Coluna 'Discount' convertida para tipo numérico (float64) com erros forçados a NaN.
   ✅ Coluna 'Subtotal' convertida para tipo numérico (float64) com erros forçados a NaN.
   ✅ Coluna 'Total' convertida para tipo numérico (float64) com erros forçados a NaN.

🚀 Processando DataFrame: compras
   ✅ Coluna 'Id' convertida para tipo numérico (float64) com erros forçados a NaN.
   ✅ Coluna 'Quantity' convertida para tipo numérico (float64) com erros forçados a NaN.
   ✅ Coluna 'Price' convertida para tipo numérico (float64) com erros forçados a NaN.

## 2.2. Tratamento Estratégico de Nulos

In [15]:
print("\n" + "="*70)
print("--- 2.2. Análise de Valores Ausentes (NaN/NaT) ---")
print("="*70)

def identificar_nulos(df, nome_df):
    """
    Calcula a contagem e o percentual de valores nulos para cada coluna.
    """
    nulos = df.isnull().sum()
    total_linhas = len(df)

    # Criar um DataFrame de resumo apenas para colunas com nulos
    nulos_df = pd.DataFrame({
        'Contagem de Nulos': nulos,
        'Percentual (%)': (nulos / total_linhas) * 100
    }).sort_values(by='Contagem de Nulos', ascending=False)

    # Filtrar apenas as colunas que realmente possuem valores nulos (> 0)
    # ─ CORREÇÃO: Usar .copy() para garantir que nulos_principais é um novo DataFrame
    nulos_principais = nulos_df[nulos_df['Contagem de Nulos'] > 0].copy()

    print(f"\n--- Resumo de Nulos no DataFrame: {nome_df} ({total_linhas} linhas) ---")

    if nulos_principais.empty:
        print("✅ Não foram encontrados valores ausentes (NaN/NaT) neste DataFrame.")
    else:
        nulos_principais['Percentual (%)'] = nulos_principais['Percentual (%)'].map('{:.2f}%'.format)
        display(nulos_principais)

        print("\nPróxima etapa: **Investigar Causa, Validar Hipótese e Documentar Decisão** para cada coluna listada.")

if dataframes:
    for nome, df in dataframes.items():
        identificar_nulos(df, nome)

======================================================================
--- 2.2. Análise de Valores Ausentes (NaN/NaT) ---
======================================================================

--- Resumo de Nulos no DataFrame: clientes (2000 linhas) ---
✅ Não foram encontrados valores ausentes (NaN/NaT) neste DataFrame.

--- Resumo de Nulos no DataFrame: entregas (2000 linhas) ---
✅ Não foram encontrados valores ausentes (NaN/NaT) neste DataFrame.

--- Resumo de Nulos no DataFrame: produtos (21 linhas) ---
✅ Não foram encontrados valores ausentes (NaN/NaT) neste DataFrame.

--- Resumo de Nulos no DataFrame: pedidos (2000 linhas) ---
✅ Não foram encontrados valores ausentes (NaN/NaT) neste DataFrame.

--- Resumo de Nulos no DataFrame: compras (2000 linhas) ---
✅ Não foram encontrados valores ausentes (NaN/NaT) neste DataFrame.

##2.3. Padronização de Texto (Strings)

In [16]:
print("\n" + "="*70)
print("--- 2.3. Padronização de Texto (Strings) ---")
print("="*70)

# Mapeamento de DataFrames e suas colunas de texto para padronizar
# Inclua aqui as colunas que você sabe que contêm strings e precisam de limpeza
colunas_para_padronizar = {
    'clientes': ['Customer_Id', 'Customer_Name', 'City', 'State', 'Region'],
    'entregas': ['Delivery_Id', 'Services', 'Status'],
    'produtos': ['Product_Id', 'Product_Name', 'Category', 'Subcategory'],
    'pedidos': ['payment', 'Purchase_Status'],
    'compras': ['Item_ID', 'Product']
}

for nome_df, df in dataframes.items():
    if nome_df in colunas_para_padronizar:
        print(f"\n🚀 Processando DataFrame: {nome_df}")
        for col in colunas_para_padronizar[nome_df]:
            if col in df.columns and df[col].dtype == 'object': # Verifica se a coluna existe e é do tipo object (string)
                # Aplica strip() e lower() e lida com possíveis valores não-string
                df[col] = df[col].astype(str).str.strip().str.lower()
                print(f"   ✅ Coluna '{col}' padronizada (minúsculas e sem espaços extras).")

                # Verificação adicional para consistência de valores únicos, útil para colunas 'status' ou 'category'
                if 'status' in col.lower() or 'category' in col.lower() or 'city' in col.lower():
                    status_unicos_antes = df[col].unique()
                    print(f"      Valores únicos em '{col}' após padronização: {status_unicos_antes[:5]}... ({len(status_unicos_antes)} únicos)")
            elif col in df.columns:
                print(f"   ⚠️ Coluna '{col}' existe, mas não é do tipo string. Pulando padronização.")
            else:
                print(f"   ❌ Coluna '{col}' não encontrada no DataFrame '{nome_df}'. Pulando.")
    else:
        print(f"\n   DataFrame '{nome_df}' não possui colunas mapeadas para padronização neste passo.")

print("\n--- Verificação Final de Padronização (Amostras) ---")
# Exibir amostras para algumas colunas padronizadas para verificação
if 'clientes' in dataframes and 'City' in dataframes['clientes'].columns:
    print("\nExemplo de 'City' em 'clientes':")
    display(dataframes['clientes']['City'].head())

if 'produtos' in dataframes and 'Category' in dataframes['produtos'].columns:
    print("\nExemplo de 'Category' em 'produtos':")
    display(dataframes['produtos']['Category'].head())

if 'pedidos' in dataframes and 'Purchase_Status' in dataframes['pedidos'].columns:
    print("\nExemplo de 'Purchase_Status' em 'pedidos':")
    display(dataframes['pedidos']['Purchase_Status'].head())

======================================================================
--- 2.3. Padronização de Texto (Strings) ---
======================================================================

🚀 Processando DataFrame: clientes
   ✅ Coluna 'Customer_Id' padronizada (minúsculas e sem espaços extras).
   ✅ Coluna 'Customer_Name' padronizada (minúsculas e sem espaços extras).
   ✅ Coluna 'City' padronizada (minúsculas e sem espaços extras).
      Valores únicos em 'City' após padronização: ['sena madureira' 'campina grande' 'cantá' 'cacoal' 'rio branco']... (109 únicos)
   ✅ Coluna 'State' padronizada (minúsculas e sem espaços extras).
   ✅ Coluna 'Region' padronizada (minúsculas e sem espaços extras).

🚀 Processando DataFrame: entregas
   ✅ Coluna 'Delivery_Id' padronizada (minúsculas e sem espaços extras).
   ✅ Coluna 'Services' padronizada (minúsculas e sem espaços extras).
   ✅ Coluna 'Status' padronizada (minúsculas e sem espaços extras).
      Valores únicos em 'Status' após padronização: ['a caminho' 'entregue' 'trânsito' 'atrasado']... (4 únicos)

🚀 Processando DataFrame: produtos
   ✅ Coluna 'Product_Id' padronizada (minúsculas e sem espaços extras).
   ✅ Coluna 'Product_Name' padronizada (minúsculas e sem espaços extras).
   ✅ Coluna 'Category' padronizada (minúsculas e sem espaços extras).
      Valores únicos em 'Category' após padronização: ['eletrônicos']... (1 únicos)
   ✅ Coluna 'Subcategory' padronizada (minúsculas e sem espaços extras).
      Valores únicos em 'Subcategory' após padronização: ['celulares, tablets e acessórios' 'áudio e vídeo' 'informática']... (3 únicos)

🚀 Processando DataFrame: pedidos
   ✅ Coluna 'payment' padronizada (minúsculas e sem espaços extras).
   ✅ Coluna 'Purchase_Status' padronizada (minúsculas e sem espaços extras).
      Valores únicos em 'Purchase_Status' após padronização: ['processando' 'em analise' 'cancelado' 'confirmado']... (4 únicos)

🚀 Processando DataFrame: compras
   ✅ Coluna 'Item_ID' padronizada (minúsculas e sem espaços extras).
   ✅ Coluna 'Product' padronizada (minúsculas e sem espaços extras).

--- Verificação Final de Padronização (Amostras) ---

Exemplo de 'City' em 'clientes':

0    sena madureira
1    campina grande
2             cantá
3            cacoal
4        rio branco
Name: City, dtype: object

Exemplo de 'Category' em 'produtos':

0    eletrônicos
1    eletrônicos
2    eletrônicos
3    eletrônicos
4    eletrônicos
Name: Category, dtype: object

Exemplo de 'Purchase_Status' em 'pedidos':

0    processando
1     em analise
2      cancelado
3    processando
4     em analise
Name: Purchase_Status, dtype: object

# 3. [S1] Validação de Chaves e Unicidade

Esta seção garante que as chaves primárias das tabelas estejam íntegras, ou seja, que cada coluna designada como chave não possua valores duplicados. Isso é fundamental para evitar a contagem dupla de pedidos ou clientes nas análises futuras.

In [19]:
print("\n" + "="*70)
print("--- 3. Validação de Chaves Primárias e Unicidade ---")
print("="*70)

# Dicionário de chaves a serem verificadas
chaves_a_verificar = {
    'clientes': 'Id',
    'entregas': 'Id',
    'produtos': 'Id',
    'pedidos': 'Id',
    'compras': 'Id',
}

# --- Checagem de Unicidade ---
print("## 3.1. Validação de Chaves Simples (PKs)")
print("-" * 50)

for nome_df, coluna_chave in chaves_a_verificar.items():
    df = dataframes[nome_df]
    duplicadas_count = df[coluna_chave].duplicated().sum()

    # Regra geral para PKs
    if duplicadas_count > 0:
        print(f"❌ **ERRO GRAVE:** Tabela {nome_df} tem {duplicadas_count} duplicatas na chave '{coluna_chave}'.")
        print("É necessário investigar e remover as duplicatas.")
    else:
        print(f"✅ Tabela {nome_df}: A chave '{coluna_chave}' está **100% ÚNICA**.")

# --- Conclusão da Validação ---
print("\n## 3.2. Conclusão da Validação")
print("-" * 50)
print("A integridade das chaves primárias principais foi confirmada, garantindo a unicidade dos dados para as próximas etapas de agregação e análise.")

======================================================================
--- 3. Validação de Chaves Primárias e Unicidade ---
======================================================================
## 3.1. Validação de Chaves Simples (PKs)
--------------------------------------------------
✅ Tabela clientes: A chave 'Id' está **100% ÚNICA**.
✅ Tabela entregas: A chave 'Id' está **100% ÚNICA**.
✅ Tabela produtos: A chave 'Id' está **100% ÚNICA**.
✅ Tabela pedidos: A chave 'Id' está **100% ÚNICA**.
✅ Tabela compras: A chave 'Id' está **100% ÚNICA**.

## 3.2. Conclusão da Validação
--------------------------------------------------
A integridade das chaves primárias principais foi confirmada, garantindo a unicidade dos dados para as próximas etapas de agregação e análise.

# 4 - Detecção e Documentação de Outliers

In [20]:
print("\n" + "="*70)
print("--- Detecção e Documentação de Outliers (Método IQR) ---")
print("="*70)

def detect_and_document_outliers_iqr(df, column_name, df_name="Unnamed DataFrame"):
    """
    Detecta e documenta outliers em uma coluna numérica de um DataFrame usando o método IQR.

    Args:
        df (pd.DataFrame): O DataFrame a ser analisado.
        column_name (str): O nome da coluna numérica para detectar outliers.
        df_name (str): Um nome para o DataFrame (para exibição).
    """
    print(f"\n🚀 Analisando o DataFrame '{df_name}', Coluna: '{column_name}'")

    # Certifica-se de que a coluna é numérica e lida com NaNs
    if not pd.api.types.is_numeric_dtype(df[column_name]):
        print(f"   ❌ A coluna '{column_name}' não é numérica. Pulando a análise de outliers.")
        return

    # Remove NaNs temporariamente para cálculo de IQR para evitar erros
    # e para que o cálculo represente apenas os valores existentes.
    data = df[column_name].dropna()
    if data.empty:
        print(f"   ⚠️ A coluna '{column_name}' não possui dados válidos para análise após remover NaNs. Pulando.")
        return

    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[column_name] < lower_bound) | (df[column_name] > upper_bound)]

    num_outliers = len(outliers)
    total_rows = len(df)

    if total_rows == 0: # Evitar divisão por zero
        percent_outliers = 0
    else:
        percent_outliers = (num_outliers / total_rows) * 100

    print(f"   > Limite Inferior (Q1 - 1.5*IQR): {lower_bound:.2f}")
    print(f"   > Limite Superior (Q3 + 1.5*IQR): {upper_bound:.2f}")
    print(f"   > Outliers encontrados: {num_outliers} ({percent_outliers:.2f}% do total de {total_rows} linhas)")

    if num_outliers > 0:
        print(f"   > Amostra de 5 outliers para '{column_name}':")
        display(outliers[[column_name]].head())
        print(f"   > Mínimo: {data.min():.2f}, Máximo: {data.max():.2f}, Média: {data.mean():.2f}, Mediana: {data.median():.2f}")
    else:
        print("   ✅ Nenhum outlier detectado para esta coluna usando o método IQR.")

    # Proposta de decisão inicial (pode ser ajustada manualmente depois)
    print("   > Decisão Inicial Proposta para Outliers:")
    if column_name in ['Price', 'P_Sevice', 'Discount', 'Subtotal', 'Total', 'Quantity']:
        if num_outliers > 0:
            print("     * Manter/Investigar: Valores extremos podem representar transações de alto valor, grandes quantidades ou preços especiais. "
                  "Removê-los pode distorcer métricas importantes. Recomenda-se investigação adicional antes de qualquer tratamento.")
        else:
            print("     * Manter: Nenhum outlier detectado.")
    elif column_name == 'Id':
        if num_outliers > 0:
            print("     * Investigar: Outliers em colunas de ID são incomuns e podem indicar erros nos dados. "
                  "Verificar se são IDs válidos com valores muito discrepantes ou erros de digitação.")
        else:
            print("     * Manter: Nenhum outlier detectado (esperado para IDs).")
    else:
        print("     * Manter: Sem regra específica para esta coluna, assumindo que outliers devem ser mantidos, "
              "mas é recomendada uma investigação mais aprofundada.")

colunas_numericas_outliers = {
    'clientes': ['Id'],
    'entregas': ['Id', 'P_Sevice'],
    'produtos': ['Id', 'Price'],
    'pedidos': ['Id', 'Discount', 'Subtotal', 'Total'],
    'compras': ['Id', 'Quantity', 'Price']
}


# Loop para aplicar a função a todas as colunas especificadas
for df_name, columns in colunas_numericas_outliers.items():
    # Certifica-se de que o DataFrame existe no dicionário 'dataframes'
    if df_name in dataframes:
        df = dataframes[df_name]
        for col in columns:
            # Certifica-se de que a coluna existe no DataFrame
            if col in df.columns:
                detect_and_document_outliers_iqr(df, col, df_name)
            else:
                print(f"   ❌ Coluna '{col}' não encontrada no DataFrame '{df_name}'. Pulando.")
    else:
        print(f"   ❌ DataFrame '{df_name}' não encontrado no dicionário 'dataframes'. Pulando.")

======================================================================
--- Detecção e Documentação de Outliers (Método IQR) ---
======================================================================

🚀 Analisando o DataFrame 'clientes', Coluna: 'Id'
   > Limite Inferior (Q1 - 1.5*IQR): -998.50
   > Limite Superior (Q3 + 1.5*IQR): 2999.50
   > Outliers encontrados: 0 (0.00% do total de 2000 linhas)
   ✅ Nenhum outlier detectado para esta coluna usando o método IQR.
   > Decisão Inicial Proposta para Outliers:
     * Manter: Nenhum outlier detectado (esperado para IDs).

🚀 Analisando o DataFrame 'entregas', Coluna: 'Id'
   > Limite Inferior (Q1 - 1.5*IQR): -998.50
   > Limite Superior (Q3 + 1.5*IQR): 2999.50
   > Outliers encontrados: 0 (0.00% do total de 2000 linhas)
   ✅ Nenhum outlier detectado para esta coluna usando o método IQR.
   > Decisão Inicial Proposta para Outliers:
     * Manter: Nenhum outlier detectado (esperado para IDs).

🚀 Analisando o DataFrame 'entregas', Coluna: 'P_Sevice'
   > Limite Inferior (Q1 - 1.5*IQR): -7.10
   > Limite Superior (Q3 + 1.5*IQR): 72.90
   > Outliers encontrados: 0 (0.00% do total de 2000 linhas)
   ✅ Nenhum outlier detectado para esta coluna usando o método IQR.
   > Decisão Inicial Proposta para Outliers:
     * Manter: Nenhum outlier detectado.

🚀 Analisando o DataFrame 'produtos', Coluna: 'Id'
   > Limite Inferior (Q1 - 1.5*IQR): -9.00
   > Limite Superior (Q3 + 1.5*IQR): 31.00
   > Outliers encontrados: 0 (0.00% do total de 21 linhas)
   ✅ Nenhum outlier detectado para esta coluna usando o método IQR.
   > Decisão Inicial Proposta para Outliers:
     * Manter: Nenhum outlier detectado (esperado para IDs).

🚀 Analisando o DataFrame 'produtos', Coluna: 'Price'
   > Limite Inferior (Q1 - 1.5*IQR): -2115.20
   > Limite Superior (Q3 + 1.5*IQR): 3871.64
   > Outliers encontrados: 1 (4.76% do total de 21 linhas)
   > Amostra de 5 outliers para 'Price':

     Price
16  4604.0

   > Mínimo: 17.90, Máximo: 4604.00, Média: 1057.95, Mediana: 769.90
   > Decisão Inicial Proposta para Outliers:
     * Manter/Investigar: Valores extremos podem representar transações de alto valor, grandes quantidades ou preços especiais. Removê-los pode distorcer métricas importantes. Recomenda-se investigação adicional antes de qualquer tratamento.

🚀 Analisando o DataFrame 'pedidos', Coluna: 'Id'
   > Limite Inferior (Q1 - 1.5*IQR): -998.50
   > Limite Superior (Q3 + 1.5*IQR): 2999.50
   > Outliers encontrados: 0 (0.00% do total de 2000 linhas)
   ✅ Nenhum outlier detectado para esta coluna usando o método IQR.
   > Decisão Inicial Proposta para Outliers:
     * Manter: Nenhum outlier detectado (esperado para IDs).

🚀 Analisando o DataFrame 'pedidos', Coluna: 'Discount'
   > Limite Inferior (Q1 - 1.5*IQR): -0.07
   > Limite Superior (Q3 + 1.5*IQR): 0.22
   > Outliers encontrados: 0 (0.00% do total de 2000 linhas)
   ✅ Nenhum outlier detectado para esta coluna usando o método IQR.
   > Decisão Inicial Proposta para Outliers:
     * Manter: Nenhum outlier detectado.

🚀 Analisando o DataFrame 'pedidos', Coluna: 'Subtotal'
   > Limite Inferior (Q1 - 1.5*IQR): -4772.48
   > Limite Superior (Q3 + 1.5*IQR): 8620.32
   > Outliers encontrados: 153 (7.65% do total de 2000 linhas)
   > Amostra de 5 outliers para 'Subtotal':

    Subtotal
7    9208.00
9    9149.97
12  18416.00
33  18416.00
46  13812.00

   > Mínimo: 17.90, Máximo: 18416.00, Média: 2671.55, Mediana: 1286.97
   > Decisão Inicial Proposta para Outliers:
     * Manter/Investigar: Valores extremos podem representar transações de alto valor, grandes quantidades ou preços especiais. Removê-los pode distorcer métricas importantes. Recomenda-se investigação adicional antes de qualquer tratamento.

🚀 Analisando o DataFrame 'pedidos', Coluna: 'Total'
   > Limite Inferior (Q1 - 1.5*IQR): -4591.30
   > Limite Superior (Q3 + 1.5*IQR): 8320.23
   > Outliers encontrados: 130 (6.50% do total de 2000 linhas)
   > Amostra de 5 outliers para 'Total':

       Total
7    9143.39
12  16319.22
33  18117.50
46  13231.32
53  12730.60

   > Mínimo: 38.54, Máximo: 18349.54, Média: 2502.08, Mediana: 1220.79
   > Decisão Inicial Proposta para Outliers:
     * Manter/Investigar: Valores extremos podem representar transações de alto valor, grandes quantidades ou preços especiais. Removê-los pode distorcer métricas importantes. Recomenda-se investigação adicional antes de qualquer tratamento.

🚀 Analisando o DataFrame 'compras', Coluna: 'Id'
   > Limite Inferior (Q1 - 1.5*IQR): -998.50
   > Limite Superior (Q3 + 1.5*IQR): 2999.50
   > Outliers encontrados: 0 (0.00% do total de 2000 linhas)
   ✅ Nenhum outlier detectado para esta coluna usando o método IQR.
   > Decisão Inicial Proposta para Outliers:
     * Manter: Nenhum outlier detectado (esperado para IDs).

🚀 Analisando o DataFrame 'compras', Coluna: 'Quantity'
   > Limite Inferior (Q1 - 1.5*IQR): -2.00
   > Limite Superior (Q3 + 1.5*IQR): 6.00
   > Outliers encontrados: 0 (0.00% do total de 2000 linhas)
   ✅ Nenhum outlier detectado para esta coluna usando o método IQR.
   > Decisão Inicial Proposta para Outliers:
     * Manter: Nenhum outlier detectado.

🚀 Analisando o DataFrame 'compras', Coluna: 'Price'
   > Limite Inferior (Q1 - 1.5*IQR): -2115.20
   > Limite Superior (Q3 + 1.5*IQR): 3871.64
   > Outliers encontrados: 101 (5.05% do total de 2000 linhas)
   > Amostra de 5 outliers para 'Price':

     Price
7   4604.0
12  4604.0
33  4604.0
46  4604.0
53  4604.0

   > Mínimo: 17.90, Máximo: 4604.00, Média: 1063.25, Mediana: 769.90
   > Decisão Inicial Proposta para Outliers:
     * Manter/Investigar: Valores extremos podem representar transações de alto valor, grandes quantidades ou preços especiais. Removê-los pode distorcer métricas importantes. Recomenda-se investigação adicional antes de qualquer tratamento.